# Generated by Django 2.2.2 on 2019-06-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLASSROOM',
            fields=[
                ('classroomid', models.IntegerField(primary_key=True, serialize=False)),
                ('weizhi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JCLASS',
            fields=[
                ('jclassid', models.IntegerField(primary_key=True, serialize=False)),
                ('startweek', models.IntegerField()),
                ('endweek', models.IntegerField()),
                ('week', models.CharField(choices=[('1', '星期一'), ('2', '星期二'), ('3', '星期三'), ('4', '星期四'), ('5', '星期五'), ('6', '星期六'), ('7', '星期日')], default='星期一', max_length=10)),
                ('jieci', models.IntegerField()),
                ('classroomid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LESSONS',
            fields=[
                ('lessionid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('lesson_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PAIKE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessionid', models.IntegerField()),
                ('teacherid', models.IntegerField()),
                ('jclassid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QIANDAO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField()),
                ('jclassid', models.IntegerField()),
                ('zhuangtai', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QINGJIA',
            fields=[
                ('qingid', models.AutoField(primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('zhuangtai', models.CharField(choices=[('1', '待审'), ('2', '同意'), ('3', '不同意')], default='待审', max_length=32)),
                ('cause', models.CharField(max_length=256)),
                ('is_xiao', models.CharField(choices=[('yes', '是'), ('no', '否')], default='否', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('studentid', models.IntegerField(primary_key=True, serialize=False)),
                ('xiid', models.IntegerField()),
                ('perid', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('age', models.IntegerField()),
                ('xclassid', models.IntegerField()),
                ('password', models.CharField(default='123456', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TEACHER',
            fields=[
                ('teacherid', models.IntegerField(primary_key=True, serialize=False)),
                ('xiid', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('age', models.IntegerField()),
                ('password', models.CharField(default='123456', max_length=256)),
                ('perid', models.CharField(max_length=32)),
                ('zhicheng', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='XCLASS',
            fields=[
                ('xclassid', models.IntegerField(primary_key=True, serialize=False)),
                ('xiid', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('teacherid', models.IntegerField()),
                ('jieshao', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='XI',
            fields=[
                ('xiid', models.IntegerField(primary_key=True, serialize=False)),
                ('xizhurenid', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('jeishao', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='XIAOJIA',
            fields=[
                ('xiajiaid', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='XUANKE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField()),
                ('lessonid', models.IntegerField()),
                ('grade', models.FloatField()),
            ],
        ),
    ]
