# Generated by Django 2.2.2 on 2019-07-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qingjia',
            name='studentid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
