# Generated by Django 2.2.2 on 2019-07-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190728_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='xuanke',
            name='jiatime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xuanke',
            name='kuangtime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xuanke',
            name='latetime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
